docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Routing: routing.md
    - Migration:
        - "V2 to V3": migration/v2-to-v3.md
site_name: zend-router
site_description: 'zend-router: Flexible routing system for HTTP applications'
repo_url: 'https://github.com/zendframework/zend-router'
copyright: 'Copyright (c) 2005-2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
